### ISSUE TITLE
Test failed when importing swiper

### ISSUE THREAD

**Issue by sstenz** [mint-vernetzt/mint-vernetzt#296]
After deactivating the test in the HeroCarousel component, the error now occurs when executing "npx nx test website".

This is the error message:

`FAIL   website  apps/website/src/utils/dataTransformer.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/sirko/Documents/workspace/mint-vernetzt/node_modules/swiper/react/swiper-react.d.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as React from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import * as React from "react";
      2 |
    > 3 | import { Swiper, SwiperSlide } from "swiper/react";
        | ^
      4 | import { Navigation, Pagination, A11y, EffectFade, Autoplay } from "swiper";
      5 |
      6 | import "swiper/css";

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (../../libs/react-components/src/lib/HeroCarousel/HeroCarousel.tsx:3:1)`

**Comment by sstenz** [comment]
I have deactivated the husky pre-push hook to push the branch to origin. Now you can have a look at it:
https://github.com/mint-vernetzt/mint-vernetzt/tree/feat/Slider-Carousel-Component
